# Generated by Django 5.1.1 on 2024-10-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city1', models.CharField(max_length=255)),
                ('city2', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
